[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_GA_MEASUREMENT_ID = "G-NWR9FRXLP3"
  VITE_GA_ENABLED = "true"
  VITE_GA_DEBUG = "true"
  VITE_GA_RESPECT_DNT = "true"
  VITE_GA_FORCE_OPT_OUT = "false"

# Optional: Set different values for different deploy contexts
[context.production.environment]
  VITE_GA_DEBUG = "false"

[context.deploy-preview.environment]
  VITE_GA_DEBUG = "true"

[context.branch-deploy.environment]
  VITE_GA_DEBUG = "true"